### ISSUE TITLE
problems with the logbook and history panel

### ISSUE THREAD

**Issue by timants** [dale3h/hassio-installer#2]
i have some problem with the logbook and history panel on homeassistant, , it just does not save it there ,

when you click on logbook from your panel it says: no logbook entries found

picture: https://gyazo.com/0dcee9b31d2f5838ff4b54c6b9050a50

and when you click on history it says : no state history found

picture:  https://gyazo.com/d082f379fb585e93db118a137d86f931

the server is running now for 1,5 days on the new rpi3b+ when i switched from the 3b to 3b+ i restored a snapshot.

hope you can help me 

thanks.

**Comment by dale3h** [comment]
Can you please check your error log to see if there are any errors relating to read/writing to the database file?

**Comment by timants** [comment]
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/static.py", line 68, in staticresource_middleware
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/real_ip.py", line 27, in real_ip_middleware
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/auth.py", line 52, in auth_middleware
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/view.py", line 104, in handle
    result = await result
  File "/usr/lib/python3.6/site-packages/homeassistant/components/history.py", line 311, in get
    entity_ids, self.filters, include_start_time_state)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/history.py", line 83, in get_significant_states
    state for state in execute(query)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/recorder/util.py", line 64, in execute
    (row.to_native() for row in qry)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/recorder/util.py", line 63, in <listcomp>
    row for row in
  File "/usr/lib/python3.6/site-packages/homeassistant/components/recorder/util.py", line 64, in <genexpr>
    (row.to_native() for row in qry)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    fetch = cursor.fetchall()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1137, in fetchall
    self.cursor, self.context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1131, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1082, in _fetchall_impl
    return self.cursor.fetchall()
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6)
, source=components/recorder/util.py>
2018-04-06 18:46:51 INFO (MainThread) [homeassistant.components.http.view] Serving /api/history/period/2018-04-05T22:00:00.000Z to 192.168.178.84 (auth: True)
2018-04-06 18:46:56 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.power_current, old_state=<state sensor.power_current=494; unit_of_measurement=Watt, friendly_name=Stroom (Nu), icon=mdi:flash-outline @ 2018-04-06T18:46:24.947497+02:00>, new_state=<state sensor.power_current=492; unit_of_measurement=Watt, friendly_name=Stroom (Nu), icon=mdi:flash-outline @ 2018-04-06T18:46:56.007874+02:00>>
2018-04-06 18:47:01 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.time, old_state=<state sensor.time=18:46; friendly_name=Time, icon=mdi:clock @ 2018-04-06T18:46:01.653564+02:00>, new_state=<state sensor.time=18:47; friendly_name=Time, icon=mdi:clock @ 2018-04-06T18:47:01.655409+02:00>>
2018-04-06 18:47:01 INFO (MainThread) `

that is the log file

**Comment by dale3h** [comment]
Based on the error `sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed (Background on this error at: http://sqlalche.me/e/4xp6)`, it appears that your database file has become corrupted somehow. This can occur when a loss of power happens, or if you unplug your Raspberry Pi before shutting it down properly.

Please stop Home Assistant (***not Hass.io***), rename the database file (`/config/home-assistant_v2.db`), and Home Assistant should create a new one when you start it back up.
